### ISSUE TITLE
Magic numbers.

### ISSUE THREAD

**Issue by Qvdpost** [lisaeindhoven/chips-and-circuits#4]
Voorkom het gebruik van magic numbers. In jullie algoritmes zijn de kosten gehardcode (1, 301, 10000). Het is beter hier een variabel (of zelfs een object!) voor te gebruiken. Dan kun je makkelijk vanuit de main die waardes aanpassen voor je algoritme.

**Comment by lisaeindhoven** [comment]
Aangepast
